### ISSUE TITLE
Calibration trimmer potentiometer on the front

### ISSUE THREAD

**Issue by fiechr** [madworm/Youyue-858D-plus#3]
Sorry for opening an issue for this, because it's more of a simple question than a problem:

Is the trimmer labeled "CAL" on the front panel used in your firmware at all? It is not mentioned anywhere - so I guess temperature correction is (only) applied by the value in the software settings as described in the docs?

**Comment by madworm** [comment]
You are 100% spot on. As I did not trace out the schematic for the thermo-couple circuit, I left that cal-potentiometer alone. I don't know what it does exactly and how it might affect the temperature reading.

"Never change a running system".

**Comment by fiechr** [comment]
Ok! Thanks for clearing that up.

I tried to make a schematic of that part of the board. I'm really not an electronics expert, so I can't guarantee everything is correct, especially not about the part _before_ the OpAmp (this diode stuff seems odd to me).
But nevertheless the part after it seems more clear: The resistance of the negative feedback loop of the OpAmp is changed by the potentiometer. This changes the gain of the amp, which means the voltage on the OUT pin changes also slightly.
So if the thermocouple measures a too low (high) temperature, the amplified voltage can be raised (lowered) by this mechanism.

So I guess it should be possible to use this trimmer without negative side effects, because the value is corrected before the software control loop. I would prefer to set it this way, because the value is device-dependent anyway.

But I could be wrong about that...

![youyue858d_cal sch](https://cloud.githubusercontent.com/assets/12040376/11060756/89cafbb2-87a2-11e5-8430-b07e70cf90b3.png)
(Updated schematic, changed direction of D10)

**Comment by madworm** [comment]
The double diodes clamp the input voltage to about +- 0.7V or so. No cold-junction compensation.

D10 is very odd...

**Comment by fiechr** [comment]
Well, D10 is actually facing in the other direction on the board. ;-)
